---
framework: mocha
preRun:
     command:
        - npm ci
        - npm run build
preMerge:
  pattern:
    - "./test/*.js"
postMerge:
  pattern: 
    - "./test/*.js"
postRun:
     command:
        - node --version
configFile: rollup.config.js
version: 1.0